export type StockIdentity = {
  ticker: string;
  name: string;
  domain?: string;
};

export const STOCK_IDENTITIES: Record<string, StockIdentity> = {
  ABBV: { ticker: "ABBV", name: "AbbVie", domain: "abbvie.com" },
  ABT: { ticker: "ABT", name: "Abbott", domain: "abbott.com" },
  ADBE: { ticker: "ADBE", name: "Adobe", domain: "adobe.com" },
  AMAT: { ticker: "AMAT", name: "Applied Materials", domain: "appliedmaterials.com" },
  AMD: { ticker: "AMD", name: "AMD", domain: "amd.com" },
  AMGN: { ticker: "AMGN", name: "Amgen", domain: "amgen.com" },
  AMZN: { ticker: "AMZN", name: "Amazon", domain: "amazon.com" },
  AAPL: { ticker: "AAPL", name: "Apple", domain: "apple.com" },
  ARM: { ticker: "ARM", name: "Arm", domain: "arm.com" },
  AVGO: { ticker: "AVGO", name: "Broadcom", domain: "broadcom.com" },
  AXP: { ticker: "AXP", name: "American Express", domain: "americanexpress.com" },
  BAC: { ticker: "BAC", name: "Bank of America", domain: "bankofamerica.com" },
  BK: { ticker: "BK", name: "BNY Mellon", domain: "bnymellon.com" },
  BLK: { ticker: "BLK", name: "BlackRock", domain: "blackrock.com" },
  BMY: { ticker: "BMY", name: "Bristol Myers Squibb", domain: "bms.com" },
  C: { ticker: "C", name: "Citigroup", domain: "citigroup.com" },
  CL: { ticker: "CL", name: "Colgate-Palmolive", domain: "colgatepalmolive.com" },
  CME: { ticker: "CME", name: "CME Group", domain: "cmegroup.com" },
  COF: { ticker: "COF", name: "Capital One", domain: "capitalone.com" },
  COIN: { ticker: "COIN", name: "Coinbase", domain: "coinbase.com" },
  COP: { ticker: "COP", name: "ConocoPhillips", domain: "conocophillips.com" },
  COST: { ticker: "COST", name: "Costco", domain: "costco.com" },
  CRM: { ticker: "CRM", name: "Salesforce", domain: "salesforce.com" },
  CSCO: { ticker: "CSCO", name: "Cisco", domain: "cisco.com" },
  CVX: { ticker: "CVX", name: "Chevron", domain: "chevron.com" },
  DHR: { ticker: "DHR", name: "Danaher", domain: "danaher.com" },
  EOG: { ticker: "EOG", name: "EOG Resources", domain: "eogresources.com" },
  GILD: { ticker: "GILD", name: "Gilead", domain: "gilead.com" },
  GIS: { ticker: "GIS", name: "General Mills", domain: "generalmills.com" },
  GOOG: { ticker: "GOOG", name: "Alphabet", domain: "google.com" },
  GOOGL: { ticker: "GOOGL", name: "Alphabet", domain: "google.com" },
  GS: { ticker: "GS", name: "Goldman Sachs", domain: "goldmansachs.com" },
  HAL: { ticker: "HAL", name: "Halliburton", domain: "halliburton.com" },
  HOOD: { ticker: "HOOD", name: "Robinhood", domain: "robinhood.com" },
  HSY: { ticker: "HSY", name: "Hershey", domain: "thehersheycompany.com" },
  IBM: { ticker: "IBM", name: "IBM", domain: "ibm.com" },
  ICE: { ticker: "ICE", name: "ICE", domain: "ice.com" },
  INTU: { ticker: "INTU", name: "Intuit", domain: "intuit.com" },
  ISRG: { ticker: "ISRG", name: "Intuitive Surgical", domain: "intuitive.com" },
  JNJ: { ticker: "JNJ", name: "Johnson & Johnson", domain: "jnj.com" },
  JPM: { ticker: "JPM", name: "JPMorgan Chase", domain: "jpmorganchase.com" },
  KHC: { ticker: "KHC", name: "Kraft Heinz", domain: "kraftheinzcompany.com" },
  KMB: { ticker: "KMB", name: "Kimberly-Clark", domain: "kimberly-clark.com" },
  KMI: { ticker: "KMI", name: "Kinder Morgan", domain: "kindermorgan.com" },
  KO: { ticker: "KO", name: "Coca-Cola", domain: "coca-colacompany.com" },
  KR: { ticker: "KR", name: "Kroger", domain: "kroger.com" },
  LLY: { ticker: "LLY", name: "Eli Lilly", domain: "lilly.com" },
  LNG: { ticker: "LNG", name: "Cheniere", domain: "cheniere.com" },
  LRCX: { ticker: "LRCX", name: "Lam Research", domain: "lamresearch.com" },
  MARA: { ticker: "MARA", name: "MARA Holdings", domain: "mara.com" },
  MCO: { ticker: "MCO", name: "Moody's", domain: "moodys.com" },
  MDT: { ticker: "MDT", name: "Medtronic", domain: "medtronic.com" },
  META: { ticker: "META", name: "Meta", domain: "meta.com" },
  MDLZ: { ticker: "MDLZ", name: "Mondelez", domain: "mondelezinternational.com" },
  MO: { ticker: "MO", name: "Altria", domain: "altria.com" },
  MPC: { ticker: "MPC", name: "Marathon Petroleum", domain: "marathonpetroleum.com" },
  MRK: { ticker: "MRK", name: "Merck", domain: "merck.com" },
  MS: { ticker: "MS", name: "Morgan Stanley", domain: "morganstanley.com" },
  MSFT: { ticker: "MSFT", name: "Microsoft", domain: "microsoft.com" },
  MSTR: { ticker: "MSTR", name: "MicroStrategy", domain: "microstrategy.com" },
  MU: { ticker: "MU", name: "Micron", domain: "micron.com" },
  NFLX: { ticker: "NFLX", name: "Netflix", domain: "netflix.com" },
  NOW: { ticker: "NOW", name: "ServiceNow", domain: "servicenow.com" },
  NVDA: { ticker: "NVDA", name: "NVIDIA", domain: "nvidia.com" },
  ORCL: { ticker: "ORCL", name: "Oracle", domain: "oracle.com" },
  OXY: { ticker: "OXY", name: "Occidental", domain: "oxy.com" },
  PANW: { ticker: "PANW", name: "Palo Alto Networks", domain: "paloaltonetworks.com" },
  PEP: { ticker: "PEP", name: "PepsiCo", domain: "pepsico.com" },
  PFE: { ticker: "PFE", name: "Pfizer", domain: "pfizer.com" },
  PG: { ticker: "PG", name: "Procter & Gamble", domain: "pg.com" },
  PLTR: { ticker: "PLTR", name: "Palantir", domain: "palantir.com" },
  PM: { ticker: "PM", name: "Philip Morris", domain: "pmi.com" },
  PNC: { ticker: "PNC", name: "PNC", domain: "pnc.com" },
  PSX: { ticker: "PSX", name: "Phillips 66", domain: "phillips66.com" },
  QCOM: { ticker: "QCOM", name: "Qualcomm", domain: "qualcomm.com" },
  RDDT: { ticker: "RDDT", name: "Reddit", domain: "reddit.com" },
  RIOT: { ticker: "RIOT", name: "Riot Platforms", domain: "riotplatforms.com" },
  RIVN: { ticker: "RIVN", name: "Rivian", domain: "rivian.com" },
  SCHW: { ticker: "SCHW", name: "Charles Schwab", domain: "schwab.com" },
  SLB: { ticker: "SLB", name: "SLB", domain: "slb.com" },
  SMCI: { ticker: "SMCI", name: "Supermicro", domain: "supermicro.com" },
  SOFI: { ticker: "SOFI", name: "SoFi", domain: "sofi.com" },
  SPGI: { ticker: "SPGI", name: "S&P Global", domain: "spglobal.com" },
  SPY: { ticker: "SPY", name: "SPDR S&P 500 ETF", domain: "spdrs.com" },
  SYY: { ticker: "SYY", name: "Sysco", domain: "sysco.com" },
  TMO: { ticker: "TMO", name: "Thermo Fisher Scientific", domain: "thermofisher.com" },
  TSLA: { ticker: "TSLA", name: "Tesla", domain: "tesla.com" },
  TXN: { ticker: "TXN", name: "Texas Instruments", domain: "ti.com" },
  UNH: { ticker: "UNH", name: "UnitedHealth Group", domain: "unitedhealthgroup.com" },
  UPST: { ticker: "UPST", name: "Upstart", domain: "upstart.com" },
  USB: { ticker: "USB", name: "U.S. Bancorp", domain: "usbank.com" },
  VLO: { ticker: "VLO", name: "Valero", domain: "valero.com" },
  WFC: { ticker: "WFC", name: "Wells Fargo", domain: "wellsfargo.com" },
  WMT: { ticker: "WMT", name: "Walmart", domain: "walmart.com" },
  XOM: { ticker: "XOM", name: "Exxon Mobil", domain: "exxonmobil.com" },
};

export function getStockIdentity(ticker: string): StockIdentity {
  const normalized = ticker.trim().toUpperCase();
  return (
    STOCK_IDENTITIES[normalized] ?? {
      ticker: normalized,
      name: normalized,
    }
  );
}
