$ErrorActionPreference = "Stop"

function Read-ExistingEnvValue {
  param([string[]] $Names)

  foreach ($name in $Names) {
    $envValue = [Environment]::GetEnvironmentVariable($name, "Process")
    if ($envValue) {
      return $envValue.Trim()
    }
  }

  foreach ($file in @(".env.local", ".env.production.local")) {
    if (-not (Test-Path -LiteralPath $file)) { continue }
    foreach ($line in Get-Content -LiteralPath $file) {
      foreach ($name in $Names) {
        if ($line -match "^\s*$([regex]::Escape($name))\s*=\s*(.*)$") {
          return ($Matches[1].Trim().Trim('"').Trim("'"))
        }
      }
    }
  }

  return ""
}

function Read-RequiredValue {
  param(
    [string] $Label,
    [string[]] $EnvNames
  )

  $existing = Read-ExistingEnvValue -Names $EnvNames
  if ($existing) {
    $answer = Read-Host "$Label found locally. Press Enter to reuse it, or paste a replacement"
    if ($answer.Trim()) { return $answer.Trim() }
    return $existing
  }

  do {
    $value = Read-Host "$Label"
    $value = $value.Trim()
  } while (-not $value)
  return $value
}

function Set-VercelSecret {
  param(
    [string] $Name,
    [string] $Value
  )

  Write-Host "Updating $Name in Vercel Production..."
  $remove = Invoke-Cmd -Command "npx.cmd vercel env rm $Name production -y" -TimeoutSeconds 120
  if ($remove.ExitCode -ne 0) {
    Write-Host "No existing $Name removed, or Vercel reported it was not present."
  }

  $add = Invoke-Cmd -Command "npx.cmd vercel env add $Name production" -InputText $Value -TimeoutSeconds 180
  if ($add.ExitCode -ne 0) {
    throw "Vercel env add failed for $Name.`n$($add.Output)"
  }

  Write-Host "$Name updated in Vercel Production."
}

function Assert-Command {
  param([string] $Name)
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "$Name is required but was not found in PATH."
  }
}

function Invoke-Cmd {
  param(
    [string] $Command,
    [string] $InputText = "",
    [int] $TimeoutSeconds = 120
  )

  $psi = New-Object System.Diagnostics.ProcessStartInfo
  $psi.FileName = "cmd.exe"
  $psi.Arguments = "/d /s /c $Command"
  $psi.UseShellExecute = $false
  $psi.RedirectStandardInput = $true
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  $psi.CreateNoWindow = $true

  $process = New-Object System.Diagnostics.Process
  $process.StartInfo = $psi
  [void]$process.Start()

  if ($InputText) {
    $process.StandardInput.WriteLine($InputText)
  }
  $process.StandardInput.Close()

  if (-not $process.WaitForExit($TimeoutSeconds * 1000)) {
    try { $process.Kill() } catch {}
    throw "Command timed out: $Command"
  }

  $output = ($process.StandardOutput.ReadToEnd() + $process.StandardError.ReadToEnd()).Trim()
  if ($output) {
    Write-Host $output
  }

  return [pscustomobject]@{
    ExitCode = $process.ExitCode
    Output = $output
  }
}

function Write-ReconnectBackup {
  param(
    [string] $ClientId,
    [string] $ClientSecret,
    [string] $CallbackUrl,
    [string] $RefreshToken
  )

  $dir = Join-Path (Get-Location) ".data"
  New-Item -ItemType Directory -Force -Path $dir | Out-Null
  $path = Join-Path $dir "schwab-reconnect-latest.env"
  $content = @(
    "# Generated by scripts/reconnect-schwab-broker.ps1"
    "# Keep this private. Delete after Vercel is verified."
    "SCHWAB_CLIENT_ID=$ClientId"
    "SCHWAB_CLIENT_SECRET=$ClientSecret"
    "SCHWAB_CALLBACK_URL=$CallbackUrl"
    "SCHWAB_REFRESH_TOKEN=$RefreshToken"
  ) -join [Environment]::NewLine
  Set-Content -LiteralPath $path -Value $content -NoNewline
  Write-Host "Private backup written to $path"
}

function New-SchwabLoginUrl {
  param(
    [string] $ClientId,
    [string] $CallbackUrl
  )

  $encodedClientId = [uri]::EscapeDataString($ClientId)
  $encodedCallback = [uri]::EscapeDataString($CallbackUrl)
  return "https://api.schwabapi.com/v1/oauth/authorize?response_type=code&client_id=$encodedClientId&redirect_uri=$encodedCallback"
}

function Get-SchwabCodeFromCallback {
  param([string] $Callback)

  $value = $Callback.Trim()
  if (-not $value) {
    throw "No callback URL was provided."
  }

  if ($value -notmatch "://" -and $value -notmatch "code=") {
    return $value
  }

  try {
    $uri = [uri]$value
    $query = $uri.Query.TrimStart("?")
  } catch {
    if ($value -match "[?&]code=([^&]+)") {
      return [uri]::UnescapeDataString($Matches[1])
    }
    throw "Could not parse the callback URL."
  }

  foreach ($pair in $query.Split("&")) {
    $parts = $pair.Split("=", 2)
    if ($parts.Length -eq 2 -and $parts[0] -eq "code") {
      return [uri]::UnescapeDataString($parts[1])
    }
  }

  throw "The callback URL does not contain a code= parameter."
}

function Request-SchwabRefreshToken {
  param(
    [string] $ClientId,
    [string] $ClientSecret,
    [string] $CallbackUrl,
    [string] $Code
  )

  $pair = "{0}:{1}" -f $ClientId, $ClientSecret
  $basic = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($pair))
  $body = @{
    grant_type = "authorization_code"
    code = $Code
    redirect_uri = $CallbackUrl
  }

  try {
    $response = Invoke-RestMethod `
      -Uri "https://api.schwabapi.com/v1/oauth/token" `
      -Method Post `
      -Headers @{
        Authorization = "Basic $basic"
        Accept = "application/json"
      } `
      -ContentType "application/x-www-form-urlencoded" `
      -Body $body `
      -TimeoutSec 45
  } catch {
    throw "Schwab token exchange failed. The authorization code may be expired, already used, or from different app credentials. Start the script again and copy the final callback URL immediately after approval."
  }

  if (-not $response.refresh_token) {
    throw "Schwab did not return a refresh token."
  }
  return [string]$response.refresh_token
}

Push-Location (Split-Path -Parent $PSScriptRoot)
try {
  Assert-Command "npx.cmd"

  Write-Host ""
  Write-Host "SPY Prophet Schwab broker reconnect"
  Write-Host "This will open Schwab, capture a fresh refresh token, update Vercel, deploy, and verify production."
  Write-Host ""

  $clientId = Read-RequiredValue -Label "Schwab Client ID / App Key" -EnvNames @("SCHWAB_CLIENT_ID", "SCHWAB_APP_KEY")
  $clientSecret = Read-RequiredValue -Label "Schwab Client Secret / App Secret" -EnvNames @("SCHWAB_CLIENT_SECRET", "SCHWAB_APP_SECRET")
  $callbackUrl = Read-ExistingEnvValue -Names @("SCHWAB_CALLBACK_URL")
  if (-not $callbackUrl) { $callbackUrl = "https://127.0.0.1" }

  $env:SCHWAB_CLIENT_ID = $clientId
  $env:SCHWAB_CLIENT_SECRET = $clientSecret
  $env:SCHWAB_CALLBACK_URL = $callbackUrl

  Write-Host ""
  Write-Host "A Schwab login window will open. After approval, copy the full final https://127.0.0.1 URL from the address bar."
  Write-Host ""

  $loginUrl = New-SchwabLoginUrl -ClientId $clientId -CallbackUrl $callbackUrl

  try {
    Set-Clipboard -Value $loginUrl
    Write-Host "Schwab login URL copied to your clipboard."
  } catch {
    Write-Host "Could not copy the Schwab login URL to your clipboard."
  }

  Write-Host ""
  Write-Host "If the browser does not open, paste this URL into Chrome:"
  Write-Host $loginUrl
  Write-Host ""

  try {
    Start-Process $loginUrl
  } catch {
    Write-Host "Automatic browser open failed. Paste the copied URL into Chrome manually."
  }

  Write-Host "After Schwab redirects to https://127.0.0.1, copy the full address-bar URL."
  Read-Host "Then come back here and press Enter"
  Write-Host ""

  $callback = ""
  try {
    $callback = (Get-Clipboard -Raw).Trim()
  } catch {
    $callback = ""
  }
  if ($callback -notmatch "code=") {
    $callback = Read-Host "Paste the full final Schwab callback URL here"
  }
  $code = Get-SchwabCodeFromCallback -Callback $callback
  $refreshToken = Request-SchwabRefreshToken -ClientId $clientId -ClientSecret $clientSecret -CallbackUrl $callbackUrl -Code $code

  Write-Host "Fresh Schwab refresh token generated."
  Write-ReconnectBackup -ClientId $clientId -ClientSecret $clientSecret -CallbackUrl $callbackUrl -RefreshToken $refreshToken

  Set-VercelSecret -Name "SCHWAB_CLIENT_ID" -Value $clientId
  Set-VercelSecret -Name "SCHWAB_CLIENT_SECRET" -Value $clientSecret
  Set-VercelSecret -Name "SCHWAB_CALLBACK_URL" -Value $callbackUrl
  Set-VercelSecret -Name "SCHWAB_REFRESH_TOKEN" -Value $refreshToken

  Write-Host ""
  Write-Host "Deploying production..."
  & npx.cmd vercel deploy --prod -y
  if ($LASTEXITCODE -ne 0) {
    throw "Production deploy failed."
  }

  Write-Host ""
  Write-Host "Verifying production broker status..."
  Start-Sleep -Seconds 6
  $status = Invoke-RestMethod -Uri "https://www.spyprophet.app/api/system/status" -TimeoutSec 90
  $options = $status.checks | Where-Object { $_.key -eq "options" } | Select-Object -First 1
  $stocks = $status.checks | Where-Object { $_.key -eq "stocks" } | Select-Object -First 1
  $spx = $status.checks | Where-Object { $_.key -eq "spx" } | Select-Object -First 1

  Write-Host ""
  Write-Host "Broker verification:"
  Write-Host ("Options: {0} - {1}" -f $options.status, $options.detail)
  Write-Host ("Stocks:  {0} - {1}" -f $stocks.status, $stocks.detail)
  Write-Host ("ES/SPX:  {0} - {1}" -f $spx.status, $spx.detail)

  if ($options.detail -match "reconnection" -or $stocks.detail -match "attention" -or $spx.detail -match "falling back") {
    throw "Schwab still is not fully connected. The new token may not belong to the same Schwab app credentials, or the Schwab app may not have market-data access enabled."
  }

  Write-Host ""
  Write-Host "Schwab broker reconnect complete."
} finally {
  Pop-Location
}
