"use client";

import { Bot, Check, CircleAlert, RefreshCw, Smartphone } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { cn } from "@/lib/utils";

type AlertStatus = {
  telegramBot: boolean;
  telegramChat: boolean;
  indicatorTelegramBot: boolean;
  indicatorTelegramChat: boolean;
  alertSecret: boolean;
  alertMemory: boolean;
  cloudMonitor: boolean;
};
type SystemCheck = {
  key: string;
  label: string;
  status: "ready" | "degraded" | "offline";
  detail: string;
};
type SystemStatus = { ok: boolean; checkedAt: string; checks: SystemCheck[] };

export function SettingsClient() {
  const [alerts, setAlerts] = useState<AlertStatus | null>(null);
  const [system, setSystem] = useState<SystemStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const [alertResponse, systemResponse] = await Promise.all([
        fetch("/api/alerts/status", { cache: "no-store" }),
        fetch("/api/system/status", { cache: "no-store" }),
      ]);
      setAlerts(alertResponse.ok ? await alertResponse.json() : null);
      setSystem(systemResponse.ok ? await systemResponse.json() : null);
    } catch {
      setAlerts(null);
      setSystem(null);
    } finally {
      setLoading(false);
    }
  }, []);
  useEffect(() => void refresh(), [refresh]);
  const checks = (system?.checks ?? []).filter((check) =>
    ["alerts", "spx", "options", "options-memory"].includes(check.key),
  );

  return (
    <div className="workspace-surface">
      <section className="grid border-b border-carbon/15 lg:grid-cols-2">
        <ConnectionField
          icon={Bot}
          number="01"
          title="Indicator bot"
          body="TradingView delivers the sequence generated by the live indicator."
          checks={[
            ["Bot token", alerts?.indicatorTelegramBot],
            ["Chat linked", alerts?.indicatorTelegramChat],
          ]}
        />
        <ConnectionField
          icon={Smartphone}
          number="02"
          title="Website monitor"
          body="The cloud monitor delivers website watch and execution events."
          checks={[
            ["Bot token", alerts?.telegramBot],
            ["Chat linked", alerts?.telegramChat],
            ["Cloud monitor", alerts?.cloudMonitor],
          ]}
          className="border-t border-carbon/15 lg:border-l lg:border-t-0"
        />
      </section>

      <section className="grid border-t border-carbon/15 xl:grid-cols-[0.62fr_1.38fr]">
        <div className="bg-[#11191c] p-5 py-10 text-white md:p-10">
          <p className="microlabel text-mineral">Phone sequence</p>
          <h2 className="mt-5 max-w-[420px] text-[28px] font-black leading-[0.98] md:text-[34px]">
            Every notification should move the decision forward.
          </h2>
        </div>
        <ol className="grid bg-white sm:grid-cols-4">
          {[
            ["01", "Watch", "Price approaches structure."],
            ["02", "Ready", "The setup is armed."],
            ["03", "Enter", "Risk and contract are defined."],
            ["04", "Exit", "The trade loop closes."],
          ].map(([number, title, body], index) => (
            <li
              key={title}
              className={cn(
                "flex min-h-[190px] flex-col p-5 md:p-7",
                index > 0 &&
                  "border-t border-carbon/15 sm:border-l sm:border-t-0",
              )}
            >
              <p className="num text-[11px] font-bold text-cobalt">{number}</p>
              <p className="mt-auto pt-12 text-[16px] font-black uppercase tracking-[0.04em]">
                {title}
              </p>
              <p className="mt-3 text-[12px] leading-relaxed text-carbon/70">
                {body}
              </p>
            </li>
          ))}
        </ol>
      </section>

      <section className="border-t border-carbon/15 bg-[#f3f2ed]">
        <div className="flex items-center border-b border-carbon p-5 md:px-10 md:py-6">
          <div>
            <p className="microlabel text-carbon/60">Readiness</p>
            <h2 className="mt-1.5 text-[19px] font-black">
              Systems that can affect a live decision
            </h2>
          </div>
          <button
            type="button"
            onClick={() => void refresh()}
            disabled={loading}
            className="ml-auto grid h-10 w-10 place-items-center border border-carbon transition-colors hover:bg-white disabled:opacity-40"
            aria-label="Refresh system status"
          >
            <RefreshCw size={16} className={loading ? "animate-spin" : ""} />
          </button>
        </div>
        {checks.length ? (
          <div>
            {checks.map((check) => (
              <HealthLine key={check.key} check={check} />
            ))}
          </div>
        ) : (
          <div className="flex items-center gap-3 p-5 text-[13px] font-semibold md:p-10">
            <CircleAlert size={16} aria-hidden="true" />
            System status is unavailable. No fallback readiness is shown.
          </div>
        )}
      </section>
    </div>
  );
}

function ConnectionField({
  icon: Icon,
  number,
  title,
  body,
  checks,
  className = "",
}: {
  icon: typeof Bot;
  number: string;
  title: string;
  body: string;
  checks: Array<[string, boolean | undefined]>;
  className?: string;
}) {
  const ready = checks.every(([, value]) => value === true);
  return (
    <article className={`min-h-[330px] bg-white/30 p-5 md:p-9 ${className}`}>
      <div className="flex items-center justify-between">
        <span className="grid h-11 w-11 place-items-center bg-carbon text-lime">
          <Icon size={19} aria-hidden="true" />
        </span>
        <span className="num text-[11px] font-bold text-carbon/65">
          {number}
        </span>
      </div>
      <p
        className={cn(
          "microlabel mt-10 inline-flex border px-2.5 py-1.5",
          ready ? "border-go-ink/30 bg-go-ink/10 text-go-ink" : "border-stop-ink/25 bg-stop-ink/10 text-stop-ink",
        )}
      >
        {ready ? "Connected" : "Needs setup"}
      </p>
      <h2 className="mt-5 text-[32px] font-black leading-none md:text-[36px]">
        {title}
      </h2>
      <p className="mt-4 max-w-[550px] text-[14px] leading-relaxed text-carbon/60">
        {body}
      </p>
      <div className="mt-8 border-t border-carbon">
        {checks.map(([label, value]) => (
          <div
            key={label}
            className="flex items-center justify-between border-b border-carbon/15 py-3 text-[12px]"
          >
            <span className="font-bold">{label}</span>
            <span
              className={cn(
                "microlabel",
                value ? "text-go-ink" : "text-stop-ink",
              )}
            >
              {value ? "Ready" : value === false ? "Missing" : "Checking"}
            </span>
          </div>
        ))}
      </div>
    </article>
  );
}

function HealthLine({ check }: { check: SystemCheck }) {
  const ready = check.status === "ready";
  return (
    <div className="grid gap-3 border-b border-carbon/15 px-5 py-5 md:grid-cols-[220px_130px_1fr] md:items-center md:px-10">
      <span className="text-[14px] font-black">{check.label}</span>
      <span
        className={cn(
          "microlabel inline-flex w-fit items-center gap-2",
          ready
            ? "text-go-ink"
            : check.status === "offline"
              ? "text-stop-ink"
              : "text-warn-ink",
        )}
      >
        {ready ? (
          <Check size={13} aria-hidden="true" />
        ) : (
          <CircleAlert size={13} aria-hidden="true" />
        )}
        {check.status}
      </span>
      <span className="text-[12px] leading-relaxed text-carbon/70">
        {check.detail}
      </span>
    </div>
  );
}
